#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Ryuichi Ueda s23C1017KB@s.chibakoudai.jp
# SPDX-License-Identifier: BSD-3-Clause
import sys

def tonum(s):
    try:
        return int(s)
    except:
        # ここで警告を出さず、0を返すように変更
        return 0

ans = 0
for line in sys.stdin:
    ans += tonum(line)

print(ans)

